version: '2'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: mdp4semaphore
    hostname: mysql
    expose:
      - 3306

  semaphore_api:
    #image: castawaylabs/semaphore
    build:
      context: .
      dockerfile: Dockerfile-development
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: mdp4semaphore
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /etc/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: mdp4admin
      SEMAPHORE_ADMIN_NAME: Default\ Administrator
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
    expose:
      - 3000
    ports:
      - 8081:3000
