FROM expansible/go_node_ansible:latest

WORKDIR "/go/src/github.com/ansible-semaphore/semaphore/public"

RUN npm install async
#RUN lessc css/semaphore.less > css/semaphore.css
#RUN pug html/*.jade html/*/*.jade html/*/*/*.jade &
RUN node ./bundler.js

RUN chmod +x /usr/bin/semaphore

ADD semaphore-startup.sh /usr/bin/semaphore-startup.sh

RUN chmod +x /usr/bin/semaphore-startup.sh

EXPOSE 3000

ENTRYPOINT ["/usr/bin/semaphore-startup.sh"]

CMD ["/usr/bin/semaphore", "-config", "/etc/semaphore/semaphore_config.json"]
